In [1]:
# Import required libraries NumPy, polynomial and matplotlib
import numpy as np
import matplotlib.pyplot as plt

# Generate two random vectors
v1=np.random.rand(10)
v2=np.random.rand(10)

# Creates a sequence of equally separated values
sequence = np.linspace(v1.min(),v1.max(), num=len(v1)*10)

# Fit the data to polynomial fit data with 4 degree of polynomial
coefs = np.polyfit(v1, v2, 3)

# Evaluate polynomial on given sequence
polynomial_sequence = np.polyval(coefs,sequence)

# plot the  polynomial curve 
plt.plot(sequence, polynomial_sequence)

# Show plot
plt.show()

<Figure size 640x480 with 1 Axes>

In [2]:
# Import numpy 
import numpy as np

# Create matrix using NumPy
mat=np.mat([[2,4],[5,7]])
print("Matrix:\n",mat)

# Calculate determinant
print("Determinant:",np.linalg.det(mat))

Matrix:
 [[2 4]
 [5 7]]
Determinant: -5.999999999999998


In [3]:
# Import numpy 
import numpy as np

# Create matrix using NumPy
mat=np.mat([[2,4],[5,7]])
print("Matrix:\n",mat)

# Find matrix inverse
inverse = np.linalg.inv(mat)
print("Inverse:\n",inverse)

Matrix:
 [[2 4]
 [5 7]]
Inverse:
 [[-1.16666667  0.66666667]
 [ 0.83333333 -0.33333333]]


In [4]:
# Create matrix A and Vector B using NumPy
A=np.mat([[1,1],[3,2]])
print("Matrix A:\n",A)

B = np.array([200,450]) 
print("Vector B:", B)

Matrix A:
 [[1 1]
 [3 2]]
Vector B: [200 450]


In [5]:
# Solve linear equations
solution = np.linalg.solve(A, B) 
print("Solution vector x:", solution)

Solution vector x: [ 50. 150.]


In [6]:
# Check the solution
print("Result:",np.dot(A,solution))

Result: [[200. 450.]]


In [1]:
# Import numpy 
import numpy as np

# Create matrix using NumPy
mat=np.mat([[2,4],[5,7]])
print("Matrix:\n",mat)

Matrix:
 [[2 4]
 [5 7]]


In [2]:
# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(mat)
print("Eigenvalues:", eigenvalues) 
print("Eigenvectors:", eigenvectors) 

Eigenvalues: [-0.62347538  9.62347538]
Eigenvectors: [[-0.83619408 -0.46462222]
 [ 0.54843365 -0.885509  ]]


In [3]:
# Compute eigenvalues 
eigenvalues= np.linalg.eigvals(mat)
print("Eigenvalues:", eigenvalues) 

Eigenvalues: [-0.62347538  9.62347538]


In [35]:
# import required libraries
import numpy as np
from scipy.linalg import svd

# Create a matrix
mat=np.array([[5, 3, 1],[5, 3, 0],[1, 0, 5]])

# Perform matrix decomposition using SVD 
U, Sigma, V_transpose = svd(mat)

print("Left Singular Matrix:",U)
print("Diagonal Matrix: ", Sigma)
print("Right Singular Matrix:", V_transpose)

Left Singular Matrix: [[-0.70097269 -0.06420281 -0.7102924 ]
 [-0.6748668  -0.26235919  0.68972636]
 [-0.23063411  0.9628321   0.14057828]]
Diagonal Matrix:  [8.42757145 4.89599358 0.07270729]
Right Singular Matrix: [[-0.84363943 -0.48976369 -0.2200092 ]
 [-0.13684207 -0.20009952  0.97017237]
 [ 0.51917893 -0.84858218 -0.10179157]]


In [42]:
# import required libraries
import numpy as np
from numpy.linalg import matrix_rank

# Create a matrix
mat=np.array([[5, 3, 1],[5, 3, 1],[1, 0, 5]])

# Compute rank of matrix
print("Matrix: \n", mat)
print("Rank:",matrix_rank(mat))

Matrix: 
 [[5 3 1]
 [5 3 1]
 [1 0 5]]
Rank: 2


In [1]:
# Import numpy 
import numpy as np

# Create an array with random values
random_mat=np.random.random((3,3))
print("Random Matrix: \n",random_mat)

Random Matrix: 
 [[0.02567004 0.76283728 0.56045752]
 [0.9108559  0.12473724 0.61271728]
 [0.81452216 0.21216752 0.41230953]]
